name: Fortify ScanCentral DAST Scan
on:
  workflow_dispatch:
  push:
    # Master or main branch that you want to trigger this workflow for
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]
jobs:
  scdast:
    runs-on: self-hosted
    steps:
      - env:
          FTFY_TOKEN: ${{ secrets.FTFY_TOKEN }}
          CICD_TOKEN: a6953011-29c9-4e51-b52c-d8e14d6122b9
        run: |
          cmd /c 'curl --location --request POST "http://10.229.222.122:64814/api/scans/start-scan-cicd" --header "Authorization: FORTIFYTOKEN $FTFY_TOKEN" --header "Content-Type: application/json" --data-raw "{\"cicdToken\":\"$CICD_TOKEN\"}"'
